version: '3.8'

services:
    db:
        image: mysql:8.0
        container_name: database
        environment:
          MYSQL_DATABASE: db
          MYSQL_ROOT_PASSWORD: 123   
          MYSQL_USER: smh                   
          MYSQL_PASSWORD: 12355           
        ports:
            - "3306:3306"
        volumes:
             - db_data:/var/lib/mysql
volumes:
    db_data:
